### ISSUE TITLE
Where "mapping" package? creation.py line 49

### ISSUE THREAD

**Issue by tkliuxing** [aparo/django-elasticsearch#2]
I use virtualenv test django-elasticsearch.
I installed aparo/django-nonrel, djangotoolbox and pyes.
When I run "python manager.py stncdb", python output the following traceback:

Traceback (most recent call last):
  File "./manage.py", line 14, in <module>
    execute_manager(settings)
  File "/home/bai/code/djes/lib/python2.6/site-packages/django/core/management/**init**.py", line 438, in execute_manager
    utility.execute()
  File "/home/bai/code/djes/lib/python2.6/site-packages/django/core/management/**init**.py", line 379, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/bai/code/djes/lib/python2.6/site-packages/django/core/management/base.py", line 191, in run_from_argv
    self.execute(_args, *_options.**dict**)
  File "/home/bai/code/djes/lib/python2.6/site-packages/django/core/management/base.py", line 220, in execute
    output = self.handle(_args, *_options)
  File "/home/bai/code/djes/lib/python2.6/site-packages/django/core/management/base.py", line 351, in handle
    return self.handle_noargs(**options)
  File "/home/bai/code/djes/lib/python2.6/site-packages/django/core/management/commands/syncdb.py", line 90, in handle_noargs
    sql, references = connection.creation.sql_create_model(model, self.style, seen_models)
  File "/home/bai/code/djes/lib/python2.6/site-packages/django_elasticsearch-0.1-py2.6.egg/django_elasticsearch/creation.py", line 49, in sql_create_model
ImportError: No module named mapping

**Comment by aparo** [comment]
Sorry missed to push. 
Just added and pushed.
Hi,
Alberto
